#!/usr/bin/env ruby
# Copyright 2011-present Fred Emmott. See COPYING file.

_DIR = File.dirname(__FILE__)
$LOAD_PATH.push(File.join(_DIR, '../lib'))

load File.join(_DIR, 'lib.rb')
require 'my_stuff/cache'

Foo.new(MyStuff::Cache::MemoryCache.new).run
